### ISSUE TITLE
More exciting python3 errors

### ISSUE THREAD

**Issue by ericfode** [Autodesk/aomi#152]
```
Connecting to https://REDACTED/
Token derived from /home/fodee/.vault-token-REDACTED
Traceback (most recent call last):
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/template.py", line 129, in render
    .render(**obj)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/templates/aws-credentials.j2", line 2, in top-level template code
    {% for key, secret in aomi_items.iteritems() -%}
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'iteritems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/cli.py", line 466, in main
    action_runner(parser, args)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/cli.py", line 445, in action_runner
    template_runner(client.connect(args), parser, args)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/cli.py", line 380, in template_runner
    args)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/render.py", line 114, in template
    template_obj)
  File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/template.py", line 140, in render
    ' '.join(template_traces))
aomi.exceptions.Validation: Validation Error - Missing template variable File "/home/fodee/src/clerk/.env/lib/python3.6/site-packages/aomi/templates/aws-credentials.j2", line 2, in top-level template code
    {% for key, secret in aomi_items.iteritems() -%}
```

**Comment by otakup0pe** [comment]
Closing this as #153 will cover it.
