### ISSUE TITLE
SSL exception running aomi thaw

### ISSUE THREAD

**Issue by jasonmichaelmartin** [Autodesk/aomi#165]
$ aomi thaw Downloads/aomi-Keys-214032-08-21-2017.ice
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/aomi", line 9, in <module>
    load_entry_point('aomi==0.13.11', 'console_scripts', 'aomi')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aomi/cli.py", line 323, in main
    action_runner(parser, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aomi/cli.py", line 287, in action_runner
    client = aomi.vault.client(args.operation, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aomi/vault.py", line 133, in client
    if not vault_client.is_authenticated():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 514, in is_authenticated
    self.lookup_token()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 423, in lookup_token
    return self._get('/v1/auth/token/lookup-self', wrap_ttl=wrap_ttl).json()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 944, in _get
    return self.__request('get', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 972, in __request
    allow_redirects=False, **_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)

**Comment by otakup0pe** [comment]
according to https://github.com/Autodesk/aomi/issues/76 we need to fix your python 🙊

**Comment by otakup0pe** [comment]
Portable tools with Python.... was a mistake. Closing this out because "out of scope".
