### ISSUE TITLE
app/user mode broken

### ISSUE THREAD

**Issue by otakup0pe** [Autodesk/aomi#17]
Related to #8 and how tokens are requested...

**Comment by otakup0pe** [comment]
```
PYTHONPATH=~/src/autodesk-aomi/ python ~/src/autodesk-aomi/aomi cicd/secrets/artifactory --verbose
Connecting to https://coev.cloud.autodesk.com/
Token derived from VAULT_APP_ID and VAULT_USER_ID
Token metadata operation REDACTED
Token metadata hostname REDACTED
Token metadata unix_user REDACTED
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/freedmj/src/autodesk-aomi/aomi/__main__.py", line 5, in <module>
    main()
  File "/Users/freedmj/src/autodesk-aomi/aomi/cli.py", line 100, in main
    action_runner(operation)
  File "/Users/freedmj/src/autodesk-aomi/aomi/cli.py", line 69, in action_runner
    client = aomi.vault.client(operation, opt)
  File "/Users/freedmj/src/autodesk-aomi/aomi/vault.py", line 113, in client
    vault_client.token = operational_token(vault_client, operation, opt)
  File "/Users/freedmj/src/autodesk-aomi/aomi/vault.py", line 90, in operational_token
    token = vault_client.create_token(**args)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/hvac/v1/__init__.py", line 386, in create_token
    return self._post('/v1/auth/token/create', json=params).json()
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/hvac/v1/__init__.py", line 643, in _post
    return self.__request('post', url, **kwargs)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/hvac/v1/__init__.py", line 678, in __request
    self.__raise_error(response.status_code, text, errors=errors)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/hvac/v1/__init__.py", line 684, in __raise_error
    raise exceptions.InvalidRequest(message, errors=errors)
hvac.exceptions.InvalidRequest: permission denied
```

**Comment by otakup0pe** [comment]
other than the lack of pretty error messages, this is expected behavior

it was a vault policy issue...
