### ISSUE TITLE
templates blow up if vault paths have hyphens

### ISSUE THREAD

**Issue by otakup0pe** [Autodesk/aomi#20]
because i guess jinja don't like that?

easy solution: swap hyphens with underscores when rendering template?

**Comment by otakup0pe** [comment]
```
aomi template foo foo.out vault/path Traceback (most recent call last): File "/usr/local/bin/aomi", line 9, in <module> load_entry_point('aomi==0.3.1', 'console_scripts', 'aomi')() File "/usr/local/lib/python2.7/dist-packages/aomi/cli.py", line 92, in main action_runner(operation, client) File "/usr/local/lib/python2.7/dist-packages/aomi/cli.py", line 79, in action_runner aomi.render.template(client, args[1], args[2], args[3]) File "/usr/local/lib/python2.7/dist-packages/aomi/render.py", line 20, in template output = template_src.render(**obj) File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render return self.environment.handle_exception(exc_info, True) File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception reraise(exc_type, exc_value, tb) File "<template>", line 7, in top-level template code TypeError: unsupported operand type
 for -: 'Undefined' and 'Undefined' 
```
