### ISSUE TITLE
No such file or directory: '.../aomi/aomi/version' without install

### ISSUE THREAD

**Issue by knotthere** [Autodesk/aomi#49]
I simply `git cloned` this repo, and attempted to run `aomi`, but that resulted in an error that:
```
IOError: [Errno 2] No such file or directory: '/Users/larry/Autodesk/aomi/aomi/version'
```
This file does exist in:
```
IOError: [Errno 2] No such file or directory: '/Users/larry/Autodesk/aomi/version'
```

The full transcript:
```
larry:~/Autodesk/Credentials$ ../aomi/aomi.py
Traceback (most recent call last):
  File "../aomi/aomi.py", line 6, in <module>
    from aomi.cli import main
  File "/Users/larry/Autodesk/aomi/aomi/cli.py", line 7, in <module>
    import aomi.vault
  File "/Users/larry/Autodesk/aomi/aomi/vault.py", line 10, in <module>
    from aomi.helpers import problems, log, cli_hash, merge_dicts
  File "/Users/larry/Autodesk/aomi/aomi/helpers.py", line 7, in <module>
    VERSION = resource_string(__name__, 'version')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1164, in resource_string
    self, resource_name
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1604, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1727, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/Users/larry/Autodesk/aomi/aomi/version'
```

**Comment by shaiguitar** [comment]
Have you tried installing this from pip? https://pypi.python.org/pypi/aomi/0.8.0

**Comment by otakup0pe** [comment]
I ran into an issue with the embedded version file not showing up in the package itself. In fixing that, I think I broke local / dev mode. Looking into this.

pip / docker should still be fine...

**Comment by otakup0pe** [comment]
I think this is fixed  in https://github.com/Autodesk/aomi/commit/cd31251526473a65570f001369a3a585076a5e50 please let me know.

**Comment by knotthere** [comment]
I just verified cd31251526473a65570f001369a3a585076a5e50 fixed the problem I was seeing - thanks!

**Comment by otakup0pe** [comment]
Hooray! I'm going to leave this issue open until a test for this gets added heh.

**Comment by otakup0pe** [comment]
added exec context [tests](https://github.com/Autodesk/aomi/blob/master/tests/integration/exec_context.bats)
