### ISSUE TITLE
Issues Reading Secrets from Vault Caused by Unicode Encodings

### ISSUE THREAD

**Issue by alpha5000** [Autodesk/aomi#54]
Just tried reading some secrets from vault, only to get the below error. I believe Aomi does not set Unicode encoding to 'UTF-8'.

Resource: https://pythonhosted.org/kitchen/unicode-frustrations.html

```
CCSC02RR6HCG8WP:scripts CentraM$ ./paas-pipeline ~/chefDev/viewing-chef-data -a build-ami -c stage
Using chef-data directory /Users/CentraM/chefDev/viewing-chef-data
Using Vault token from /Users/CentraM/.vault-token
latest: Pulling from paas-pipeline
Digest: sha256:2cba83089d4e49583e88e33c6f72d225ca22a710996bf2b3b91427acb5928eda
Status: Image is up to date for artifactory.adskengineer.net/paas-pipeline:latest
Using Docker image artifactory.adskengineer.net/paas-pipeline:latest
Using pipeline tools in system path
Retrieving AWS credentials from vault
Waiting on AWS credentials
..
Extracting chef secrets
Traceback (most recent call last):
  File "/usr/bin/aomi", line 9, in <module>
    load_entry_point('aomi==0.9.2', 'console_scripts', 'aomi')()
  File "/usr/lib/python2.7/site-packages/aomi/cli.py", line 166, in main
    action_runner(operation)
  File "/usr/lib/python2.7/site-packages/aomi/cli.py", line 135, in action_runner
    aomi.render.raw_file(client, args[1], args[2])
  File "/usr/lib/python2.7/site-packages/aomi/render.py", line 84, in raw_file
    open(os.path.abspath(dest), 'w').write(secret)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 1669-1670: ordinal not in range(128)
Problem: Unable to extract chef validator
```

**Comment by otakup0pe** [comment]
wait so what was the conclusion here

**Comment by alpha5000** [comment]
False alarm, there was an issue with the seeded secret, and aomi was
kicking back a Python text parsing exception. Its all working now.

On Tue, Oct 25, 2016 at 6:34 PM, Jonathan Freedman <notifications@github.com
