### ISSUE TITLE
Error running `aomi seed`

### ISSUE THREAD

**Issue by jasonmichaelmartin** [Autodesk/aomi#76]
I have set my VAULT_TOKEN as the root token.  I verified connectivity with `vault mounts`
I created a “Secretfile” and .secret directory where I have copied my ids_rsa and ids_rsa_pub keys. ( based on your docs )
I ran `aomi seed`  and it fails with the below error

Traceback (most recent call last):
  File "/usr/local/bin/aomi", line 9, in <module>
    load_entry_point('aomi==0.11.3', 'console_scripts', 'aomi')()
  File "/Library/Python/2.7/site-packages/aomi-0.11.3-py2.7.egg/aomi/cli.py", line 178, in main
  File "/Library/Python/2.7/site-packages/aomi-0.11.3-py2.7.egg/aomi/cli.py", line 139, in action_runner
  File "/Library/Python/2.7/site-packages/aomi-0.11.3-py2.7.egg/aomi/vault.py", line 112, in client
  File "/Library/Python/2.7/site-packages/hvac-0.2.16-py2.7.egg/hvac/v1/__init__.py", line 470, in is_authenticated
  File "/Library/Python/2.7/site-packages/hvac-0.2.16-py2.7.egg/hvac/v1/__init__.py", line 414, in lookup_token
  File "/Library/Python/2.7/site-packages/hvac-0.2.16-py2.7.egg/hvac/v1/__init__.py", line 894, in _get
  File "/Library/Python/2.7/site-packages/hvac-0.2.16-py2.7.egg/hvac/v1/__init__.py", line 922, in __request
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests-2.11.1-py2.7.egg/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

**Comment by otakup0pe** [comment]
What is the point release of `python` on this host? Also, try again with the most recent version  - should be [0.13.11](https://pypi.python.org/pypi/aomi/0.13.11)

**Comment by jasonmichaelmartin** [comment]
Python 
Python 2.7.12

Same error
$ aomi seed
Traceback (most recent call last):
  File "/usr/local/bin/aomi", line 9, in <module>
    load_entry_point('aomi==0.13.11', 'console_scripts', 'aomi')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aomi/cli.py", line 323, in main
    action_runner(parser, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aomi/cli.py", line 287, in action_runner
    client = aomi.vault.client(args.operation, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/aomi/vault.py", line 133, in client
    if not vault_client.is_authenticated():
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 514, in is_authenticated
    self.lookup_token()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 423, in lookup_token
    return self._get('/v1/auth/token/lookup-self', wrap_ttl=wrap_ttl).json()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 944, in _get
    return self.__request('get', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hvac/v1/__init__.py", line 972, in __request
    allow_redirects=False, **_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)

**Comment by otakup0pe** [comment]
This could be a local Python issue. Definitely try in a virtualenv https://github.com/ianunruh/hvac/issues/75

**Comment by otakup0pe** [comment]
Gonna close this since pretty sure it was a local env issue...
