### ISSUE TITLE
error on builtin-list

### ISSUE THREAD

**Issue by otakup0pe** [Autodesk/aomi#77]
```
Traceback (most recent call last):
  File "/Users/freedmj/opt/pyz/bin/aomi", line 11, in <module>
    sys.exit(main())
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/cli.py", line 323, in main
    action_runner(parser, args)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/cli.py", line 302, in action_runner
    template_runner(client, parser, args)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/cli.py", line 264, in template_runner
    aomi.template.builtin_list()
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/template.py", line 99, in builtin_list
    for template in abspath(resource_listdir(__name__, "templates")):
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/helpers.py", line 49, in abspath
    if raw.find('/') != -1:
AttributeError: 'list' object has no attribute 'find'
```

probably related to fs compat helper ?

**Comment by otakup0pe** [comment]
Fixed this in local branch... was vaguely related to the os/path stuff.

**Comment by otakup0pe** [comment]
Fixed in https://github.com/Autodesk/aomi/commit/6ed5c4b1739e5be184d028d1d8c752835c53b64c
