### ISSUE TITLE
aomi freeze not working

### ISSUE THREAD

**Issue by otakup0pe** [Autodesk/aomi#79]
Looks to only be a problem with keybase users. Might have to do with the python2/3 work and the `helpers.flatten` function...

```
Traceback (most recent call last):
  File "/Users/freedmj/opt/pyz/bin/aomi", line 11, in <module>
    sys.exit(main())
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/cli.py", line 323, in main
    action_runner(parser, args)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/cli.py", line 310, in action_runner
    aomi.filez.freeze(args.icefile, args)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/filez.py", line 120, in freeze
    ice_file = freeze_encrypt(dest_dir, zip_filename, config, opt)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/filez.py", line 96, in freeze_encrypt
    pgp_keys = grok_keys(config, opt)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/filez.py", line 35, in grok_keys
    key_id = from_keybase(key[8:], opt)
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/filez.py", line 24, in from_keybase
    if not import_gpg_key(key):
  File "/Users/freedmj/opt/pyz/lib/python2.7/site-packages/aomi/gpg.py", line 83, in import_gpg_key
    output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 212, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
AttributeError: 'list' object has no attribute 'rfind'
```

**Comment by otakup0pe** [comment]
Fixed in https://github.com/Autodesk/aomi/commit/6ed5c4b1739e5be184d028d1d8c752835c53b64c
